### PR TITLE
Add pagination to the users#show page (fixes #22)

### LINKED ISSUE #22: Implement pagination on user ratings page.
Implement pagination on user ratings page.

### PR DESCRIPTION
**Pull request by nevinera**
I also had to make the rating partial visible again - I assume it was off because you were working on styling or something, but the pagination wouldn't be very impressive if it paginated an empty list ;-)

### CODE REVIEW

**Comment by Amit-P-Amin** [comment]
Wow, that's a great gem! So much easier than pagination through backbone. Thanks!

Yeah - I disabled it because I wanted the feature off until I figured out whether or not people are okay with showing their ratings publicly.

**Comment by nevinera** [comment]
Ah, I gotcha. Should have looked at the commit log, I guess.

**Comment by nevinera** [comment]
I turned the ratings back off via data control in the controller until you get opt-in set up or something :-)

**Comment by Amit-P-Amin** [comment]
Excellent.

**Comment by Amit-P-Amin** [comment]
The gem works great! Better than what I custom coded for backbone.

**Pull request merged**
